version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: i18n
    versions:
    - 1.8.7
    - 1.8.8
    - 1.8.9
  - dependency-name: faker
    versions:
    - 2.15.1
    - 2.16.0
  - dependency-name: parser
    versions:
    - 3.0.0.0
  - dependency-name: ffi
    versions:
    - 1.14.2
