default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: jp_development
  adapter:  mysql2
  encoding: utf8
  host:     localhost
  username: root

test:
  <<: *default
  database: jp_test
  adapter:  mysql2
  encoding: utf8
  host:     localhost
  username: root

production:
  <<: *default
  database: app_ranking_app
  adapter:  mysql2
  encoding: utf8
  host:     <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
