rankings:
  ios_apps:
    top_free:
      title: 'iOS Apps Top Free Ranking'
    top_paid:
      title: 'iOS Apps Top Paid Ranking'
  itunes_music:
    top_songs:
      title: 'iTunes Music Top Songs Ranking'
  apple_music:
    top_songs:
      title: 'Apple Music Top Songs Ranking'
  audiobooks:
    top_audiobooks:
      title: 'Audiobooks Top Audiobooks Ranking'
