rankings:
  ios_apps:
    top_free:
      title: 'Top Free iOS Apps'
    top_paid:
      title: 'Top Paid iOS Apps'
  ios_games:
    top_free:
      title: 'Top Free iOS Games'
    top_paid:
      title: 'Top Paid iOS Games'
  itunes_music:
    top_songs:
      title: 'Top iTunes Music'
  apple_music:
    top_songs:
      title: 'Top Apple Music'
  audiobooks:
    top_audiobooks:
      title: 'Top Audiobooks'
  books:
    top_free:
      title: 'Top Free Books'
    top_paid:
      title: 'Top Paid Books'
  movies:
    top_movies:
      title: 'Top Movies'
  itunes_u:
    top_itunes_u_courses:
      title: 'Top iTunes U Courses'
